### ISSUE TITLE
How can I treat illuminations independently on Zeiss Z.1 LS

### ISSUE THREAD

**Issue by max-brambach** [m-albert/MVRegFus#1]
Hi,
Thanks a lot for your great tool! 
One question: is it possible to fuse the different illuminations (left and right lightsheet) independently? So basically to treat then as 'views' instead of fusing them before registering the views.
Best,
Max

**Comment by m-albert** [comment]
Hi @max-brambach,

as discussed elsewhere, this section of the configuration in the template script can be used to specify how to treat the illuminations and views.

https://github.com/m-albert/MVRegFus/blob/53b959ca6a1da8d51a8298ca5ad126704844575c/bin/mvregfus_run.py#L45-L78

In my experience, treating illuminations as separate views only slightly improves the image quality of the output, and fusing them into single views (i.e. without specifying `view_dict` or `'ill' = None`) before multi-view fusion is much more performant when dealing with many views.
